// Generated by `base orm schema:diff`. Do not edit by hand.
// Regenerate by changing your entities and re-running schema:diff.

import { customType, index, integer, primaryKey, real, sqliteTable, text, unique } from 'drizzle-orm/sqlite-core';

const customDateTime = customType<{ data: Date; driverData: string }>({
    dataType() {
        return 'text';
    },
    toDriver(value: Date): string {
        return value.toISOString();
    },
    fromDriver(value: string): Date {
        return new Date(value);
    },
});

export const orm_test_entity = sqliteTable('orm_test_entity', {
    id: text('id').notNull().primaryKey(),
    name: text('name').notNull(),
    age: integer('age').notNull(),
    email: text('email'),
    status: text('status'),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_composite_entity = sqliteTable('orm_composite_entity', {
    userId: text('userId').notNull(),
    projectId: text('projectId').notNull(),
    role: text('role').notNull(),
    assignedAt: customDateTime('assignedAt').notNull(),
}, (table) => [
    primaryKey({ columns: [table.userId, table.projectId] }),
]);

export const orm_comment_entity = sqliteTable('orm_comment_entity', {
    id: text('id').notNull().primaryKey(),
    content: text('content').notNull(),
    authorId: text('authorId').notNull(),
    postId: text('postId').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_post_entity = sqliteTable('orm_post_entity', {
    id: text('id').notNull().primaryKey(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    authorId: text('authorId').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_user_entity = sqliteTable('orm_user_entity', {
    id: text('id').notNull().primaryKey(),
    username: text('username').notNull(),
    email: text('email').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_categories = sqliteTable('orm_categories', {
    id: integer('id').notNull().primaryKey(),
    name: text('name').notNull().unique(),
    slug: text('slug').notNull().unique(),
    description: text('description'),
    parentId: integer('parentId'),
    sortOrder: integer('sortOrder').notNull().default(0),
    isVisible: integer('isVisible', { mode: 'boolean' }).notNull().default(true),
    createdAt: customDateTime('createdAt').notNull(),
});

export const orm_orders = sqliteTable('orm_orders', {
    id: integer('id').notNull().primaryKey(),
    orderNumber: text('orderNumber').notNull().unique().$defaultFn(() => `ORD-${Date.now()}`),
    customerId: integer('customerId').notNull(),
    status: text('status').notNull().default("pending"),
    subtotal: real('subtotal').notNull().default(0),
    tax: real('tax').notNull().default(8.5),
    shipping: real('shipping').notNull().default(12),
    total: real('total').notNull().$defaultFn(function () {
            return 20.5;
        }),
    currency: text('currency').notNull().default("USD"),
    metadata: text('metadata', { mode: 'json' }),
    orderDate: customDateTime('orderDate').notNull().$defaultFn(() => new Date()),
    shippedDate: customDateTime('shippedDate'),
    deliveredDate: customDateTime('deliveredDate'),
    createdAt: customDateTime('createdAt').notNull(),
}, (table) => [
    index('idx_order_date').on(table.orderDate),
    index('idx_customer_status').on(table.customerId, table.status),
]);

export const orm_products = sqliteTable('orm_products', {
    id: text('id').notNull().primaryKey(),
    name: text('name').notNull(),
    sku: text('sku').notNull().unique(),
    vendorCode: text('vendorCode'),
    description: text('description').notNull().default("No description available"),
    price: real('price').notNull().default(99.99),
    stockQuantity: integer('stockQuantity').notNull().default(10),
    isActive: integer('isActive', { mode: 'boolean' }).notNull().default(true),
    status: text('status').notNull().default("draft"),
    weight: real('weight').default(0),
    specifications: text('specifications', { mode: 'json' }),
    publishedAt: customDateTime('publishedAt').notNull().$defaultFn(() => new Date()),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
}, (table) => [
    index('idx_price_status').on(table.price, table.status),
    index('idx_sku').on(table.sku),
    unique('uq_sku_vendor').on(table.sku, table.vendorCode),
]);

export const orm_product_categories = sqliteTable('orm_product_categories', {
    productId: text('productId').notNull(),
    categoryId: integer('categoryId').notNull(),
}, (table) => [
    primaryKey({ columns: [table.productId, table.categoryId] }),
]);

export const orm_product_tags = sqliteTable('orm_product_tags', {
    productId: text('productId').notNull(),
    tagId: text('tagId').notNull(),
}, (table) => [
    primaryKey({ columns: [table.productId, table.tagId] }),
]);

export const orm_tags = sqliteTable('orm_tags', {
    name: text('name').notNull().primaryKey(),
    color: text('color').notNull().default("#000000"),
    usageCount: integer('usageCount').notNull().default(0),
});

export const orm_articles = sqliteTable('orm_articles', {
    id: text('id').notNull().primaryKey(),
    title: text('title').notNull(),
    content: text('content').notNull(),
    authorId: text('writer_id').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_authors = sqliteTable('orm_authors', {
    id: text('id').notNull().primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    code: text('code').notNull().unique(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_books = sqliteTable('orm_books', {
    id: text('id').notNull().primaryKey(),
    title: text('title').notNull(),
    isbn: text('isbn').notNull().unique(),
    pages: integer('pages').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});

export const orm_book_genre_mapping = sqliteTable('orm_book_genre_mapping', {
    bookId: text('book_id').notNull(),
    genreId: text('genre_id').notNull(),
}, (table) => [
    primaryKey({ columns: [table.bookId, table.genreId] }),
]);

export const orm_genres = sqliteTable('orm_genres', {
    id: text('id').notNull().primaryKey(),
    name: text('name').notNull().unique(),
    description: text('description'),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt').notNull(),
});
