// Copyright 2026 System, Inc.
// SPDX-License-Identifier: Apache-2.0

export const RPC_ERROR_CODE_NOT_FOUND = 'NOT_FOUND';
export const RPC_ERROR_CODE_NOT_ALLOWED = 'NOT_ALLOWED';
export const RPC_ERROR_CODE_MALFORMED_RESPONSE = 'MALFORMED_RESPONSE';
export const RPC_ERROR_CODE_VALIDATION_ERROR = 'VALIDATION_ERROR';
export const RPC_ERROR_CODE_INTERNAL_ERROR = 'INTERNAL_ERROR';

export type RpcErrorCode =
    | typeof RPC_ERROR_CODE_NOT_FOUND
    | typeof RPC_ERROR_CODE_NOT_ALLOWED
    | typeof RPC_ERROR_CODE_MALFORMED_RESPONSE
    | typeof RPC_ERROR_CODE_VALIDATION_ERROR
    | typeof RPC_ERROR_CODE_INTERNAL_ERROR;
