// Copyright 2026 System, Inc.
// SPDX-License-Identifier: Apache-2.0

import { JsonObject } from '../../json/Json';

export interface RpcEnvelope<MetadataType extends JsonObject = JsonObject> {
    /**
     * A unique identifier generated by the client for the RPC call.
     * This can be a UUID v4, a counter, or any unique string.
     */
    id: string;

    /**
     * Optional cross-cutting metadata.
     */
    meta?: MetadataType;

    /**
     * The version of the RPC protocol being used.
     */
    __version: '1.0';

    /**
     * The protocol used for the RPC.
     * This is a constant value that indicates the base RPC protocol.
     * It can be used as a means to determine the type of envelope being processed.
     */
    __protocol: 'BaseRPC';
}
