// Copyright 2026 System, Inc.
// SPDX-License-Identifier: Apache-2.0

import * as fs from 'fs';
import * as path from 'path';

import { BaseSettings } from '@system-inc/base-foundation/base/BaseSettings';
import { BaseAppManifest } from '@system-inc/base-foundation/configuration/BaseAppManifest';
import { OrmDatabaseType } from '@system-inc/base-foundation/orm/database/adapter/OrmDatabaseType';
import { ormRequireTable } from '@system-inc/base-foundation/orm/metadata/OrmSchemaRegistry';
import { OrmSchemaBuilderDrizzleMySql } from '@system-inc/base-foundation/orm/schema/drizzle/OrmSchemaBuilderDrizzleMySql';
import { OrmSchemaBuilderDrizzleSQLite } from '@system-inc/base-foundation/orm/schema/drizzle/OrmSchemaBuilderDrizzleSQLite';
import { BaseWorkerProject } from '../../project/BaseWorkerProject';

/**
 * Ensures the Drizzle boilerplate exists, creating it if necessary.
 *
 * The layout is single-directory per database — one migration timeline
 * per DB rather than per (DB × environment). All envs share the same
 * migration files; deploy-time release tracking gates promotion.
 *
 * @returns The path to the drizzle config file
 */
export function ormGetDrizzleBoilerplate(
    workerProject: BaseWorkerProject,
    environment: string,
    databaseName: string,
    databaseType: OrmDatabaseType,
): string {
    const drizzlePath = ormGetDrizzleBoilerplatePath(
        workerProject,
        databaseName,
    );

    const configPath = path.join(drizzlePath, 'drizzle.config.ts');
    const generatedSchemaPath = path.join(drizzlePath, 'schema.generated.ts');
    const releasePath = path.join(drizzlePath, 'release.ts');
    const migrationsPath = path.join(drizzlePath, 'migrations');

    const stateExisted =
        fs.existsSync(generatedSchemaPath) &&
        fs.existsSync(releasePath) &&
        fs.existsSync(migrationsPath);

    fs.mkdirSync(drizzlePath, { recursive: true });
    fs.mkdirSync(migrationsPath, { recursive: true });

    const dialect = databaseType.dialect;
    const driver = getDriver(databaseType);
    const needsCredentials = databaseType.driver !== 'durable';

    // Paths are emitted relative to the worker folder. `ormRunDrizzleCommand`
    // spawns drizzle-kit with `cwd: workerProject.workerFolder`, so these
    // resolve to the same files regardless of where the user invoked
    // `base orm ...` from (project root, workspace root, worker dir, etc.).
    const schemaPathRelative = `./database/${databaseName}/drizzle/schema.generated.ts`;
    const outPathRelative = `./database/${databaseName}/drizzle/migrations`;

    // Regenerate the config only when it drifts from what we'd generate now.
    // This retrofits new fields (e.g. the tablesFilter env read) onto older
    // configs and tracks dialect/path changes, without rewriting every run.
    // Each worker tracks its own migration history in its own table. Workers
    // that share a database otherwise collide on the default `__drizzle_migrations`
    // table — drizzle decides "applied?" by the single latest `created_at` across
    // the whole table, so one worker's rows silently skip another's migrations.
    const migrationsTable = drizzleMigrationsTableName(workerProject.worker);

    const expectedConfig = buildDrizzleConfigContent(
        dialect,
        driver,
        needsCredentials,
        schemaPathRelative,
        outPathRelative,
        migrationsTable,
    );
    const currentConfig = fs.existsSync(configPath)
        ? fs.readFileSync(configPath, 'utf8')
        : undefined;
    if (currentConfig !== expectedConfig) {
        fs.writeFileSync(configPath, expectedConfig);
    }

    // Stub schema.generated.ts so the boilerplate is complete on first run.
    // The real content is written by ormWriteDrizzleSchemaFile() before
    // drizzle-kit runs. The file is pure drizzle (no foundation imports, no
    // decorators) so drizzle-kit's bundled loader never touches our framework
    // code.
    if (!fs.existsSync(generatedSchemaPath)) {
        fs.writeFileSync(
            generatedSchemaPath,
            `// Generated by \`base orm schema:generate\`. Run that command to populate.
export {};
`,
        );
    }

    if (!fs.existsSync(releasePath)) {
        fs.writeFileSync(releasePath, RELEASE_FILE_INITIAL_CONTENT);
    }

    console.log(
        stateExisted
            ? `✓ Drizzle boilerplate ready at: ${drizzlePath}`
            : `✅ Drizzle boilerplate created at: ${drizzlePath}`,
    );

    return configPath;
}

/**
 * Ensures the local-D1 variant of the drizzle config exists —
 * `drizzle.local.config.ts` beside the main config. It targets wrangler's
 * local sqlite directly (plain `sqlite` dialect, no `d1-http` driver), with
 * the file path arriving through the same BASE_DRIZZLE_CREDENTIALS env read
 * as remote credentials, so the generated file stays static and
 * machine-independent. Used by `base orm db:studio --local`.
 *
 * @returns The path to the local drizzle config file
 */
export function ormGetDrizzleLocalD1Boilerplate(
    workerProject: BaseWorkerProject,
    databaseName: string,
): string {
    const drizzlePath = ormGetDrizzleBoilerplatePath(
        workerProject,
        databaseName,
    );
    fs.mkdirSync(drizzlePath, { recursive: true });

    const configPath = path.join(drizzlePath, 'drizzle.local.config.ts');
    const expectedConfig = buildDrizzleConfigContent(
        'sqlite',
        undefined,
        true,
        `./database/${databaseName}/drizzle/schema.generated.ts`,
        `./database/${databaseName}/drizzle/migrations`,
        drizzleMigrationsTableName(workerProject.worker),
    );
    const currentConfig = fs.existsSync(configPath)
        ? fs.readFileSync(configPath, 'utf8')
        : undefined;
    if (currentConfig !== expectedConfig) {
        fs.writeFileSync(configPath, expectedConfig);
    }
    return configPath;
}

/**
 * Builds the `drizzle.config.ts` source. It's a static file that reads per-run
 * values — credentials and the table filter — from env vars that
 * `ormRunDrizzleCommand` populates before invoking drizzle-kit. Keeping it free
 * of a settings import means drizzle-kit's bundled loader never walks
 * foundation's parameter decorators. `tablesFilter` scopes `push`
 * (`schema:sync`) to this worker's tables; when the env var is unset (e.g.
 * `schema:sync --all-tables`) it resolves to `undefined`, i.e. all tables.
 */
function buildDrizzleConfigContent(
    dialect: string,
    driver: string | undefined,
    needsCredentials: boolean,
    schemaPathRelative: string,
    outPathRelative: string,
    migrationsTable: string,
): string {
    let content = `import '@system-inc/base-foundation/startup/preload';

import { defineConfig } from 'drizzle-kit';

`;
    if (needsCredentials) {
        content += `const dbCredentials = JSON.parse(
    process.env.BASE_DRIZZLE_CREDENTIALS ||
        '{}', // populated by base-cli's ormRunDrizzleCommand
);

`;
    }
    content += `const tablesFilter = process.env.BASE_DRIZZLE_TABLES_FILTER
    ? process.env.BASE_DRIZZLE_TABLES_FILTER.split(',')
    : undefined;

export default defineConfig({
    dialect: '${dialect}',`;
    if (driver) {
        content += `
    driver: '${driver}',`;
    }
    if (needsCredentials) {
        content += `
    dbCredentials,`;
    }
    content += `
    schema: '${schemaPathRelative}',
    out: '${outPathRelative}',
    tablesFilter,
    migrations: {
        table: '${migrationsTable}',
    },
});
`;
    return content;
}

/**
 * The drizzle migration-tracking table for a worker — `__drizzle_migrations_<worker>`,
 * sanitized to a valid identifier and capped at MySQL's 64-char limit. Per-worker
 * so workers sharing a database keep independent migration histories instead of
 * fighting over the default `__drizzle_migrations` table.
 */
export function drizzleMigrationsTableName(worker: string): string {
    const slug = worker
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '_')
        .replace(/^_+|_+$/g, '');
    return `__drizzle_migrations_${slug}`.slice(0, 64);
}

/**
 * Resolves the entities listed in settings, serializes the drizzle
 * schema, and writes it to schema.generated.ts. Runs in our CLI's
 * ts-node environment so decorators resolve normally — drizzle-kit
 * never has to deal with them.
 */
/**
 * Generates the drizzle schema source from the worker's entity decorators
 * without touching disk. Used by both `ormWriteDrizzleSchemaFile` (which
 * persists the result) and `base orm schema:check` (which only needs to
 * compare against the on-disk file).
 */
export function ormGenerateDrizzleSchemaSource(
    databaseName: string,
    settings: BaseSettings,
): string {
    const ormSettings = settings.orm?.[databaseName];
    if (!ormSettings) {
        throw new Error(
            `Cannot generate drizzle schema: no ORM settings for database '${databaseName}'`,
        );
    }

    // Collect the entity metadata, then run the dual-output schema
    // builder. The builder produces the runtime drizzle objects we
    // discard here AND the source code we write to disk — both from
    // the same code path, so source and runtime can't drift.
    const appManifest = BaseAppManifest.fromSettings(settings);
    const ormManifestEntry = appManifest.getOrmSettings(databaseName);
    const dbMetadata = ormManifestEntry.entities
        .map((entity) => ormRequireTable(entity))
        .filter((m) => m !== undefined);

    const builder =
        ormSettings.databaseType.dialect === 'mysql'
            ? new OrmSchemaBuilderDrizzleMySql()
            : new OrmSchemaBuilderDrizzleSQLite();

    builder.createSchema(dbMetadata);
    return builder.getEmittedSource();
}

export function ormWriteDrizzleSchemaFile(
    workerProject: BaseWorkerProject,
    databaseName: string,
    settings: BaseSettings,
): void {
    const source = ormGenerateDrizzleSchemaSource(databaseName, settings);
    const drizzlePath = ormGetDrizzleBoilerplatePath(
        workerProject,
        databaseName,
    );
    // schema:generate writes the schema before ormGetDrizzleBoilerplate has
    // created the database folder, so ensure it exists for a fresh database.
    fs.mkdirSync(drizzlePath, { recursive: true });
    fs.writeFileSync(path.join(drizzlePath, 'schema.generated.ts'), source);
}

/**
 * Returns the absolute path to a database's generated schema file.
 * Exposed so `base orm schema:check` can read the on-disk version to
 * compare against a freshly-generated one.
 */
export function ormGetDrizzleSchemaPath(
    workerProject: BaseWorkerProject,
    databaseName: string,
): string {
    return path.join(
        ormGetDrizzleBoilerplatePath(workerProject, databaseName),
        'schema.generated.ts',
    );
}

export interface OrmSchemaCheckResult {
    upToDate: boolean;
    schemaPath: string;
    reason?: 'missing-file' | 'mismatch' | 'no-owned-tables';
}

/**
 * Verifies the on-disk `schema.generated.ts` matches what the worker's
 * entities would produce right now. Shared by `base orm schema:check`
 * and the per-worker `CheckWorker` so the two code paths can't disagree.
 */
export function ormCheckDrizzleSchema(
    workerProject: BaseWorkerProject,
    databaseName: string,
    settings: BaseSettings,
): OrmSchemaCheckResult {
    const schemaPath = ormGetDrizzleSchemaPath(workerProject, databaseName);

    // A worker that owns no tables in this database has nothing to generate and
    // therefore nothing to check — all its entities here are external
    // (externalSchema/externalEntities) or inherited (inheritSchema), so the
    // schema is owned/migrated by another worker. Treat as up-to-date instead of
    // demanding a schema.generated.ts that should not exist.
    const ownedEntities =
        BaseAppManifest.fromSettings(settings).getOrmSettings(
            databaseName,
        ).entities;
    if (ownedEntities.length === 0) {
        return { upToDate: true, schemaPath, reason: 'no-owned-tables' };
    }

    if (!fs.existsSync(schemaPath)) {
        return { upToDate: false, schemaPath, reason: 'missing-file' };
    }
    const expected = ormGenerateDrizzleSchemaSource(databaseName, settings);
    const actual = fs.readFileSync(schemaPath, 'utf8');
    if (normalizeSchemaSource(actual) !== normalizeSchemaSource(expected)) {
        return { upToDate: false, schemaPath, reason: 'mismatch' };
    }
    return { upToDate: true, schemaPath };
}

/**
 * Normalize line endings + trailing whitespace before comparison so a
 * CRLF/LF mismatch (e.g. Windows checkout vs Linux CI) doesn't false-fail.
 */
function normalizeSchemaSource(source: string): string {
    return source
        .replace(/\r\n/g, '\n')
        .replace(/[ \t]+$/gm, '')
        .trimEnd();
}

/**
 * Gets the path to the drizzle directory (single per database, no
 * per-environment subdirs).
 */
export function ormGetDrizzleBoilerplatePath(
    workerProject: BaseWorkerProject,
    databaseName: string,
): string {
    return path.join(
        workerProject.workerFolder,
        'database',
        databaseName,
        'drizzle',
    );
}

/**
 * Checks if drizzle boilerplate exists for the database.
 */
export function drizzleBoilerplateExists(
    workerProject: BaseWorkerProject,
    databaseName: string,
): boolean {
    const drizzlePath = ormGetDrizzleBoilerplatePath(
        workerProject,
        databaseName,
    );
    return (
        fs.existsSync(path.join(drizzlePath, 'drizzle.config.ts')) &&
        fs.existsSync(path.join(drizzlePath, 'schema.generated.ts')) &&
        fs.existsSync(path.join(drizzlePath, 'migrations'))
    );
}

/**
 * Maps our internal driver to the value drizzle-kit expects in its
 * `driver` config field. drizzle-kit's naming is its own convention.
 */
function getDriver(databaseType: OrmDatabaseType): string | undefined {
    switch (databaseType.driver) {
        case 'd1':
            return 'd1-http';
        case 'durable':
            return 'durable-sqlite';
        case 'planetscale':
        case 'better-sqlite':
            return undefined;
    }
}

/**
 * Drizzle-kit emits migrations.js with bare ESM imports. The JSON one
 * (`import journal from './meta/_journal.json'`) is rejected by Node 22
 * in ESM mode without `with { type: 'json' }`. wrangler/esbuild also
 * needs the attribute in newer versions when bundling ESM.
 *
 * Add the attribute to JSON imports. SQL imports stay bare — wrangler's
 * [[rules]] Text loader handles them at bundle time.
 *
 * Result: same file works in both contexts. Worker bundle: esbuild
 * inlines via its loaders. Node 22 ESM: import attribute is honored.
 */
export function ormAddJsonImportAttribute(
    workerProject: BaseWorkerProject,
    databaseName: string,
): void {
    const migrationsJsPath = path.join(
        ormGetDrizzleBoilerplatePath(workerProject, databaseName),
        'migrations',
        'migrations.js',
    );

    if (!fs.existsSync(migrationsJsPath)) {
        return;
    }

    const original = fs.readFileSync(migrationsJsPath, 'utf8');

    if (/from\s+['"][^'"]+\.json['"]\s+with\s+\{/.test(original)) {
        return;
    }

    const rewritten = original.replace(
        /(import\s+\w+\s+from\s+['"][^'"]+\.json['"])(\s*;?)/g,
        "$1 with { type: 'json' }$2",
    );

    if (rewritten !== original) {
        fs.writeFileSync(migrationsJsPath, rewritten);
    }
}

const RELEASE_FILE_INITIAL_CONTENT = `// Migration tags that have been released — never modified after this.
// Squash / regenerate is only allowed for migrations NOT in this list.
//
// Add new tags here (or run \`base orm migration:release\`) when ready
// to deploy. \`base deploy\` refuses any non-Development environment if
// migrations on disk are missing from this list.
export default {
    released: [] as string[],
};
`;
