// Generated by `base orm schema:diff`. Do not edit by hand.
// Regenerate by changing your entities and re-running schema:diff.

import { boolean, char, datetime, decimal, float, index, int, json, mysqlTable, primaryKey, text, unique, varchar } from 'drizzle-orm/mysql-core';

export const orm_test_entity = mysqlTable('orm_test_entity', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    name: varchar('name', { length: 255 }).notNull(),
    age: int('age').notNull(),
    email: varchar('email', { length: 255 }),
    status: varchar('status', { length: 50 }),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_composite_entity = mysqlTable('orm_composite_entity', {
    userId: varchar('userId', { length: 36 }).notNull(),
    projectId: varchar('projectId', { length: 36 }).notNull(),
    role: varchar('role', { length: 255 }).notNull(),
    assignedAt: datetime('assignedAt', { fsp: 6, mode: 'date' }).notNull(),
}, (table) => [
    primaryKey({ columns: [table.userId, table.projectId] }),
]);

export const orm_comment_entity = mysqlTable('orm_comment_entity', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    content: text('content').notNull(),
    authorId: char('authorId', { length: 36 }).notNull(),
    postId: char('postId', { length: 36 }).notNull(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_post_entity = mysqlTable('orm_post_entity', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    title: varchar('title', { length: 255 }).notNull(),
    content: text('content').notNull(),
    authorId: char('authorId', { length: 36 }).notNull(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_user_entity = mysqlTable('orm_user_entity', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    username: varchar('username', { length: 255 }).notNull(),
    email: varchar('email', { length: 255 }).notNull(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_categories = mysqlTable('orm_categories', {
    id: int('id', { unsigned: true }).autoincrement().notNull().primaryKey(),
    name: varchar('name', { length: 100 }).notNull().unique(),
    slug: varchar('slug', { length: 100 }).notNull().unique(),
    description: text('description'),
    parentId: int('parentId'),
    sortOrder: int('sortOrder').notNull().default(0),
    isVisible: boolean('isVisible').notNull().default(true),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_orders = mysqlTable('orm_orders', {
    id: int('id', { unsigned: true }).autoincrement().notNull().primaryKey(),
    orderNumber: varchar('orderNumber', { length: 20 }).notNull().unique().$defaultFn(() => `ORD-${Date.now()}`),
    customerId: int('customerId').notNull(),
    status: varchar('status', { length: 20 }).notNull().default("pending"),
    subtotal: decimal('subtotal', { mode: 'number', precision: 10, scale: 2 }).notNull().default(0),
    tax: decimal('tax', { mode: 'number', precision: 10, scale: 2 }).notNull().default(8.5),
    shipping: decimal('shipping', { mode: 'number', precision: 10, scale: 2 }).notNull().default(12),
    total: decimal('total', { mode: 'number', precision: 10, scale: 2 }).notNull().$defaultFn(function () {
            return 20.5;
        }),
    currency: varchar('currency', { length: 10 }).notNull().default("USD"),
    metadata: json('metadata'),
    orderDate: datetime('orderDate', { fsp: 6, mode: 'date' }).notNull().$defaultFn(() => new Date()),
    shippedDate: datetime('shippedDate', { fsp: 6, mode: 'date' }),
    deliveredDate: datetime('deliveredDate', { fsp: 6, mode: 'date' }),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
}, (table) => [
    index('idx_order_date').on(table.orderDate),
    index('idx_customer_status').on(table.customerId, table.status),
]);

export const orm_products = mysqlTable('orm_products', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    sku: varchar('sku', { length: 50 }).notNull().unique(),
    vendorCode: varchar('vendorCode', { length: 20 }),
    description: varchar('description', { length: 512 }).notNull().default("No description available"),
    price: decimal('price', { mode: 'number', precision: 10, scale: 2 }).notNull().default(99.99),
    stockQuantity: int('stockQuantity').notNull().default(10),
    isActive: boolean('isActive').notNull().default(true),
    status: varchar('status', { length: 20 }).notNull().default("draft"),
    weight: float('weight').default(0),
    specifications: json('specifications'),
    publishedAt: datetime('publishedAt', { fsp: 6, mode: 'date' }).notNull().$defaultFn(() => new Date()),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
}, (table) => [
    index('idx_price_status').on(table.price, table.status),
    index('idx_sku').on(table.sku),
    unique('uq_sku_vendor').on(table.sku, table.vendorCode),
]);

export const orm_product_categories = mysqlTable('orm_product_categories', {
    productId: varchar('productId', { length: 36 }).notNull(),
    categoryId: int('categoryId').notNull(),
}, (table) => [
    primaryKey({ columns: [table.productId, table.categoryId] }),
]);

export const orm_product_tags = mysqlTable('orm_product_tags', {
    productId: varchar('productId', { length: 36 }).notNull(),
    tagId: varchar('tagId', { length: 50 }).notNull(),
}, (table) => [
    primaryKey({ columns: [table.productId, table.tagId] }),
]);

export const orm_tags = mysqlTable('orm_tags', {
    name: varchar('name', { length: 50 }).notNull().primaryKey(),
    color: varchar('color', { length: 7 }).notNull().default("#000000"),
    usageCount: int('usageCount').notNull().default(0),
});

export const orm_articles = mysqlTable('orm_articles', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    title: varchar('title', { length: 255 }).notNull(),
    content: text('content').notNull(),
    authorId: char('writer_id', { length: 36 }).notNull(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_authors = mysqlTable('orm_authors', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    name: varchar('name', { length: 100 }).notNull(),
    email: varchar('email', { length: 255 }).notNull().unique(),
    code: varchar('code', { length: 50 }).notNull().unique(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_books = mysqlTable('orm_books', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    title: varchar('title', { length: 255 }).notNull(),
    isbn: varchar('isbn', { length: 13 }).notNull().unique(),
    pages: int('pages').notNull(),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});

export const orm_book_genre_mapping = mysqlTable('orm_book_genre_mapping', {
    bookId: varchar('book_id', { length: 36 }).notNull(),
    genreId: varchar('genre_id', { length: 36 }).notNull(),
}, (table) => [
    primaryKey({ columns: [table.bookId, table.genreId] }),
]);

export const orm_genres = mysqlTable('orm_genres', {
    id: char('id', { length: 36 }).notNull().primaryKey(),
    name: varchar('name', { length: 100 }).notNull().unique(),
    description: text('description'),
    createdAt: datetime('createdAt', { fsp: 6, mode: 'date' }).notNull(),
    updatedAt: datetime('updatedAt', { fsp: 6, mode: 'date' }).notNull(),
});
