// Generated by `base orm schema:diff`. Do not edit by hand.
// Regenerate by changing your entities and re-running schema:diff.

import { customType, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

const customDateTime = customType<{ data: Date; driverData: string }>({
    dataType() {
        return 'text';
    },
    toDriver(value: Date): string {
        return value.toISOString();
    },
    fromDriver(value: string): Date {
        return new Date(value);
    },
});

export const counter = sqliteTable('counter', {
    id: text('id').notNull().primaryKey(),
    key: text('key').notNull(),
    value: integer('value').notNull(),
    createdAt: customDateTime('createdAt').notNull(),
    updatedAt: customDateTime('updatedAt'),
});
